export const data = [
  {
    proj: 'assets/angular_bf.png',
    title: 'BuzzFeed',
    sub: 'Replica of BuzzFeed Web Page, capturing the fun and engaging essence of the original site, created by me to demonstrate my web development and design skills.',
    tech: 'Angular, TypeScript, JavaScript, HTML, CSS',
    view: 'https://angular-buzz-feed-seven.vercel.app',
    code: 'https://github.com/KarimeLinhares/Angular_BuzzFeed.git',
  },
  {
    proj: 'assets/angular_blog.png',
    title: 'Blog',
    sub: 'Personal Blog Page, with a clean and intuitive design, visitors can easily navigate through articles.',
    tech: 'Angular, TypeScript, JavaScript, HTML, CSS',
    view: 'https://angular-blog-opal.vercel.app',
    code: 'https://github.com/KarimeLinhares/Angular--Blog.git',
  },
  {
    proj: 'assets/psn.png',
    title: 'PSN Store',
    sub: 'A web Page that replicates the PlayStation Network interface, offering a similar experience for purchasing games. It was designed with an intuitive interface.',
    tech: 'Angular, TypeScript, JavaScript, HTML, CSS',
    view: 'https://angular-ps-nstore.vercel.app',
    code: 'https://github.com/KarimeLinhares/Angular_PSNstore.git',
  },
  {
    proj: 'assets/bank.png',
    title: 'Digital Bank',
    sub: 'A Digital Bank Application, an easy and quick way to manage your finances. With an intuitive interface.',
    tech: 'TypeScript, JavaScript, Jest, Express, NodeJs, HTML, CSS',
    view: 'https://typescript-bank.netlify.app',
    code: 'https://github.com/KarimeLinhares/TypeScriptBank---desafio03.git',
  },
  {
    proj: 'assets/buddys.png',
    title: 'Social Page',
    sub: 'A social Web Page, with an intuitive design and interactive features, users can create profiles for their furry friends.',
    tech: 'React, JavaScript, HTML, CSS',
    view: 'https://buddys-eight.vercel.app',
    code: 'https://github.com/KarimeLinhares/Buddys.git',
  },
  {
    proj: 'assets/animais_fantasticos.png',
    title: 'Web Page',
    sub: 'This page is about the fascinating world of animals. Featuring a variety of species, each section offers a unique and informative look at their characteristics, behaviors and habitat.',
    tech: 'JavaScript, HTML, CSS',
    view: 'https://karimelinhares.github.io/Animais-Fantasticos/',
    code: 'https://github.com/KarimeLinhares/Animais-Fantasticos.git',
  },
  {
    proj: 'assets/find.png',
    title: 'Git Search',
    sub: 'Git Search, is an application that allows users to search repositories on GitHub based on the user name. This project demonstrates skills integrating with the GitHub API, manipulating data, and developing intuitive user interfaces.',
    tech: 'React, JavaScript, HTML, CSS',
    view: 'https://git-find-eta.vercel.app',
    code: 'https://github.com/KarimeLinhares/GitFind.git',
  },
];
